// src/components/header.svelte
<script lang="ts">
	import { goto } from '$app/navigation'
	import { page } from "$app/stores"
	
	export let hide = false;
	export let mobileExpand = false;
	export let collapsed = false;
	
	let title;
	let subtitle;
	let searchbar;
	
	$: active = $page.path.startsWith($$props.href);
	$: activeExact = $page.path === $$props.href;
	
	// toggles toe mobile nav menu
	function toggleNav() { mobileExpand = !mobileExpand }
</script>

<div class="header" class:hide>
	<div class="navbar" class:mobileExpand class:collapsed>
		<h1 class="title-mobile" on:click={() => goto("/")} > TransDB.de </h1>
		
		<nav on:click={toggleNav}>
			<a href="/" class:activeExact>Startseit</a>
			<a href="/search" class:active>Suche</a>
			<a href="/manage" class:active>Management</a>
			<a href="/submit" class:active>Neuer Eintrag</a>
		</nav>
		
		<span on:click={toggleNav} class="mobileNav">
			<!--MenuIcon class:mobileExpand-->
		</span>
	</div>
	
	<h1 class="title" bind:this={title} on:click={() => goto("/")}>Trans*DB</h1>
	
	<h2 class="subtitle" bind:this={subtitle}>Die Suchmaschine für trans* relevante Angebote</h2>
	
	<!--SearchBar class="searchbar" bind:this={searchbar} placeholder="Suche nach Postleitzahl oder Ort" mobilePlaceholder="Suche nach PLZ oder Ort" on:search={search}></SearchBar-->
	
</div>

<style lang="scss">
	@import "../scss/shadows";
	@import "../scss/lengths";
	
	$background-img-width: 1625px;
	$header-height-expanded: 325px;
	$header-height-collapsed: 56px;
	
	.header {
		display: flex;
		flex-direction: column;
		align-items: center;
		
		padding: 40px 0 0 0;
		height: $header-height-expanded;
		width: 100%;
		overflow: hidden;
		
		box-shadow: $rim-shadow-regular;
		transition: 0.4s ease opacity, 0.4s ease height, 0s ease box-shadow;
		font-family: "Poppins", sans-serif;
		
		&:after {
			top: 0;
			left: 0;
			width: 100%;
			height: 56px;
			position: fixed;
			content: " ";
			z-index: 1;
		}
		
		&, &:after {
			background-image: var(--banner-overlay), var(--banner-gradient);
			background-position: top left;
			background-attachment: fixed;
			background-size: calc(min(200vw, $background-img-width)) auto, calc(min(200vw, $background-img-width));
		}
		
		@media only screen and (min-width: $background-img-width) {
			&, &:after {
				background-position: top;
				background-size: auto 325px, cover;
			}
		}
		
		&.hide {
			height: 56px;
			transition: 0.4s ease opacity, 0.4s ease height, 0.8s ease box-shadow 0.2s;
			box-shadow: $no-shadow;
			
			& .title, & .subtitle, & .search-bar {
				opacity: 0!important;
				margin: 0;
				padding: 0;
			}
		}
		
		.title, .subtitle, .search-bar {
			transition: 0.3s ease-out all;
		}
		
		.title {
			color: #fff;
			font-size: 56px;
			text-shadow: $edge-shaodw-large;
			margin: 20px 0;
			cursor: pointer;
			user-select: none;
		}
		
		.subtitle {
			margin: 0 0 40px;
			color: white;
			text-shadow: $edge-sahdow-medium;
			text-align: center;
		}
		
		/** make all children of header appear in front of background */
		& > * {
			z-index: 10;
		}
	}
	
	.navbar {
		/** z-index higher than other children of .header, for mouse event priority */
		z-index: 100;
		
		display: flex;
		justify-content: space-between;
		width: 100%;
		color: white;
		text-shadow: $edge-shadow-small;
		position: fixed;
		top: 0;
		
		transition: 0s ease box-shadow;
		
		&.collapsed {
			box-shadow: $rim-shadow-regular;
		}
		
		.header.hide & {
			@keyframes show-shadow {
				0% {
					box-shadow: 0 0 5px rgba(0, 0, 0, 0), 0 0 10px rgba(0, 0, 0, 0), 0 0 20px rgba(0, 0, 0, 0);
				}
				100% {
					box-shadow: 0 0 4px var(--color-text-shadow-strong), 0 0 8px var(--color-box-shadow-rim), 0 0 16px var(--color-box-shadow-glow);
				}
			}
			
			box-shadow: 0 0 5px rgba(0, 0, 0, 0), 0 0 10px rgba(0, 0, 0, 0), 0 0 20px rgba(0, 0, 0, 0);
			animation-name: show-shadow;
			animation-duration: 0.8s;
			animation-delay: 0.2s;
			animation-timing-function: ease;
			animation-fill-mode: forwards;
		}
		
		.title-mobile {
			margin: 0;
			font-size: 24px;
			padding: 10px;
			cursor: pointer;
		}
		
		nav {
			display: flex;
			
			a {
				color: var(--color-edge-bright);
				display: flex;
				justify-content: center;
				align-items: center;
				text-decoration: none;
				font-weight: 500;
				font-size: 20px;
				margin: 10px 10px;
				position: relative;
				cursor: pointer;
				
				&:after {
					transition: 0.2s ease width, 0.2s ease opacity;
					display: inline-block;
					width: 0;
					content: "";
					opacity: 0;
					border-bottom: 3px solid var(--color-nav-link);
					box-shadow: 0.2px 0.5px 2px var(--color-box-shadow-strong), 0.5px 1.5px 4px var(--color-box-shadow-rim), 0 0 8px var(--color-box-shadow-glow);
					position: absolute;
					bottom: 0;
				}
				
				&:hover:after {
					width: 100%!important;
					opacity: 1;
				}
				
				&.activeExact:after, &.active:after {
					opacity: 1;
					width: 70%;
				}
			}
		}
	}
	
</style>

// components/header/Header.vue
<template>
	
	<div :class="{ header: true, hide: hide }">
	
		<div :class="{navbar: true, expand, background}" ref="navbar">
	
			<h1 @click="reload">TransDB.de</h1>
			
			<nav @click="expand = !expand">
				<nuxt-link to="/" class="index">Startseite</nuxt-link>
				<nuxt-link to="/search">Suche</nuxt-link>
				
				<nuxt-link to="/manage" v-if="$store.state.user">Management</nuxt-link>
				<nuxt-link to="/submit" >Neuer Eintrag</nuxt-link>
			</nav>
			
			<span @click="expand = !expand" class="mobile">
				<MenuIcon :expand="expand" />
			</span>
			
		</div>
		
		<h1 ref="title" v-on:click="$router.push('/search')">Trans*DB</h1>
		
		<h2 ref="subtitle">Finde Angebote für trans* Personen in deiner Umgebung</h2>
		
		<SearchBar ref="searchbar" placeholder="Suche nach Postleitzahl oder Ort" mobilePlaceholder="Suche nach PLZ oder Ort" @search="search"></SearchBar>
		
	</div>
	
</template>

<script>
import SearchBar from "@/components/header/SearchBar";
import MenuIcon from "@/components/header/MenuIcon";
import AccountMixin from "@/mixins/account";
import MouseoverMixin from "@/mixins/mouseover";
import { LogOutIcon } from 'vue-feather-icons';

export default {
	name: "Header",
	components: { SearchBar, MenuIcon, LogOutIcon },
	mixins: [ AccountMixin, MouseoverMixin ],
	data() {
		return {
			hide: !["/","/search"].includes(this.$route.path),
			expand: false,
			background: false
		}
	},
	mounted() {
		this.$addScrollEvent(this.scrollEvent);
	},
	beforeDestroy() {
	   this.$removeScrollEvent(this.scrollEvent);
	},
	watch: {

		$route(to, from) {
			this.hide = !["/","/search"].includes(to.path);
		}
		
	},
	
	methods: {
		
		async reload() {
			window.location.href = "/";
		},
		
		search(newQuery) {
			this.$router.push({ name: "search", query: {...this.$route.query, ...newQuery} });
		},

		scrollEvent(scroll) {

			let percent = (scroll / (this.$el.scrollHeight - this.$refs.navbar.scrollHeight ));
			
			let opacity = (1 - percent).toFixed(2);
			opacity = opacity > 0 ? opacity: 0;
			
			this.$refs.title.style.opacity = opacity;
			this.$refs.subtitle.style.opacity = opacity;
			this.$refs.searchbar.$el.style.opacity= opacity;
			
			this.background = percent > 1;

		}
		
	}
}
</script>

<style scoped>

.header {
	display: flex;
	flex-direction: column;
	align-items: center;

	box-shadow: 0 0 4px var(--color-text-shadow-strong), 0px 0px 8px var(--color-box-shadow-rim), 0px 0px 16px var(--color-box-shadow-glow);
	padding: 40px 0 0 0;
	height: 325px;
	width: 100%;
	transition: 0.4s ease opacity, 0.4s ease height;
	overflow: hidden;
	font-family: "Poppins", sans-serif;

	transition: box-shadow 0 ease 0;
}

/** Background Image */
.header, .header:after {
	background-image: var(--banner-overlay), var(--banner-gradient);
	background-position: top left;
	background-attachment: fixed;
	background-size: calc(min(200vw, 1625px)) auto, calc(min(200vw, 1625px));
}

@media only screen and (min-width: 1625px) {
	.header, .header:after {
		background-position: top;
		background-size: auto 325px, cover;
	}
}

.header.hide {
	height: 56px;
	transition: box-shadow 0.8s ease 0.2s;
	box-shadow: 0px 0px 5px rgba(0, 0, 0, 0), 0px 0px 10px rgba(0, 0, 0, 0), 0px 0px 20px rgba(0, 0, 0, 0);
}

.header > h1, .header > h2, .header > .search-bar {
	transition: 0.3s ease-out all;
}

.header.hide > h1, .header.hide > h2, .header.hide > .search-bar {
	opacity: 0!important;
	margin: 0;
	padding: 0;
}

.header > h1 {
	color: #fff;
	font-size: 56px;
	text-shadow: 1px 1px 3px var(--color-text-shadow-strong), 2px 3px 8px var(--color-text-shadow-rim), 0 0 24px var(--color-text-shadow-glow);
	margin: 20px 0;
	cursor: pointer;
	user-select: none;
}

.header > h2 {
	margin: 0 0 40px;
	color: white;
	text-shadow: 0.3px 0.8px 2.5px var(--color-text-shadow-strong), 1px 2px 6px var(--color-text-shadow-rim), 0 0 18px var(--color-text-shadow-glow);
	text-align: center;
}

/** make all children of header appear in front of background */
.header > * {
	z-index: 10;
}

.header > .navbar {
	display: flex;
	justify-content: space-between;
	width: 100%;
	color: white;
	text-shadow: 0.5px 0.5px 2px var(--color-text-shadow-strong), 0.5px 1px 3px var(--color-text-shadow-rim), 0 0 8px var(--color-text-shadow-glow);
	position: fixed;
	top: 0;

	transition: box-shadow 0 ease 0;

	/** z-index higher than other children of .header, for mouse event priority */
	z-index: 100;
}

/** fixed background strip, which is always visible */
.header:after {
	top: 0;
	left: 0;
	width: 100%;
	height: 56px;
	position: fixed;
	content: " ";
	z-index: 1;
}

.header > .navbar.background {
	box-shadow: 0 0 4px var(--color-text-shadow-strong), 0px 0px 8px var(--color-box-shadow-rim), 0px 0px 16px var(--color-box-shadow-glow);
}


.header.hide > .navbar {
	box-shadow: 0px 0px 5px rgba(0, 0, 0, 0), 0px 0px 10px rgba(0, 0, 0, 0), 0px 0px 20px rgba(0, 0, 0, 0);
	animation-name: show-shadow;
	animation-duration: 0.8s;
	animation-delay: 0.2s;
	animation-timing-function: ease;
	animation-fill-mode: forwards;
}

@keyframes show-shadow {
	0% {
		box-shadow: 0px 0px 5px rgba(0, 0, 0, 0), 0px 0px 10px rgba(0, 0, 0, 0), 0px 0px 20px rgba(0, 0, 0, 0);
	}
	100% {
		box-shadow: 0 0 4px var(--color-text-shadow-strong), 0px 0px 8px var(--color-box-shadow-rim), 0px 0px 16px var(--color-box-shadow-glow);
	}
}

.header > .navbar > h1 {
	grid-column: 1;
	margin: 0;
	font-size: 24px;
	padding: 10px;
	cursor: pointer;
}

.header > .navbar > nav {
	grid-column: 3;
	display: flex;
}

.header > .navbar > nav > a {
	color: var(--color-nav-link);
	display: flex;
	justify-content: center;
	align-items: center;
	text-decoration: none;
	font-weight: 500;
	font-size: 20px;
	margin: 10px 10px;
	position: relative;
	cursor: pointer;
}

/** makes .hightlight nav links look like a knockout button */
/*
.header > .navbar > nav > .highlight {
	background: var(--image-background) top / 150vw 325px fixed;
	background-clip: text;
	color: transparent;
	text-shadow: none;
	font-weight: 600;
	padding: 0 6px;
}

.header > .navbar > nav > .highlight:before {
	content: "";
	display: block;
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	z-index: -1;
	background-color: var(--color-nav-link);
	box-shadow: 0 3px 6px var(--color-box-shadow);
	border-radius: 4px;
}*/

.header > .navbar > nav > a:not( .highlight ):after {
	transition: 0.2s ease width, 0.2s ease opacity;
	display: inline-block;
	width: 0;
	content: "";
	opacity: 0;
	border-bottom: 3px solid var(--color-nav-link);
	box-shadow: 0.2px 0.5px 2px var(--color-box-shadow-strong), 0.5px 1.5px 4px var(--color-box-shadow-rim), 0 0 8px var(--color-box-shadow-glow);
	position: absolute;
	bottom: 0;
}

.header > .navbar > nav > a:not( .highlight ):hover:after {
	width: 100%!important;
}

.header > .navbar > nav > a:not( .highlight ):hover:after,
.header > .navbar .nuxt-link-active:not( .index ):not( .highlight ):after,
.header > .navbar .nuxt-link-exact-active:not( .highlight ):after {
	opacity: 1;
	width: 70%;
}

.mobile {
	display: none;
	padding: 0 10px;
	align-items: center;
	cursor: pointer;
	grid-column: 3;
	grid-row: 1;
}

.mobile > .feather {
	width: 36px;
	height: 36px;
}

@media only screen and (max-width: 720px) {
	
	.mobile {
		display: flex;
	}
	
	.header {
		height: 250px;
	}
	
	.header > h2 {
		display: none;
	}
	
	.header > .navbar > nav {
		opacity: 0;
		width: 0;
		height: 0;
		overflow: hidden;
	}
	
	.navbar.expand {
		background: var(--color-mobile-nav) !important;
		
		z-index: 100;
	}

	.navbar.expand:after {
		display: none;
	}
	
	.navbar.expand > nav {
		position: absolute;
		grid-column: none;
		align-items: center;
		width: 100%;
		height: auto;
		opacity: 1;
		top: 53px;
		left: 0;
		display: flex;
		flex-direction: column;
		background-color: var(--color-mobile-nav);

		z-index: 100;
	}
	
	.navbar.expand > nav > a {
		font-size: 24px;
		padding: 5px;
	}
	
}

</style>
