// src/components/entry.svelte
<script lang="ts">
	import type { Entry } from "$models/entry.model"
	import { subjectMapping, typeMapping, offerMapping, attributeMapping } from "$lib/entryMappings"
	import mouseOverTexts from "$lib/mouseOverTexts"
	
	import Tag from "$components/tag.svelte"
	import LightButton from "$components/lightButton.svelte"
	
	import PhoneIcon from "lucide-icons-svelte/phone.svelte"
	import MapIcon from "lucide-icons-svelte/map.svelte"
	import MailIcon from "lucide-icons-svelte/mail.svelte"
	import GlobeIcon from "lucide-icons-svelte/globe.svelte"
	import EditIcon from "lucide-icons-svelte/edit.svelte"
	import Share2Icon from "lucide-icons-svelte/share2.svelte"
	
	export let entry: Entry = null;
	
	$: isWithSubject = subjectMapping[entry.type];
	$: subjectName = isWithSubject ? subjectMapping[entry.type][entry.meta.subject] : null;
	
	let addressText = "";
	$: {
		if (entry.address.street) addressText += entry.address.street + " ";
		if (entry.address.house) addressText += entry.address.house + ", ";
		if (entry.address.plz) addressText += entry.address.plz + " ";
		
		addressText += entry.address.city;
	}
</script>

<div class="entry">
	<div class="data">
		<h1>
			{entry.name}
			
			{#if entry.accessible === "yes"}
				<span class="special-tag green"> Barrierefrei </span>
			{:else if entry.accessible === "no"}
				<span class="special-tag orange"> Nicht Barrierefrei </span>
			{/if}
		</h1>
		
		<p class="small-gap">
			<b> {entry.firstName} {entry.lastName} </b>
			
			{#if isWithSubject}
				<span> {subjectName} </span>
			{:else}
				<span title={mouseOverTexts[entry.type]}> {typeMapping[entry.type]} </span>
			{/if}
		</p>
		
		<p>
			<a href={`https://www.google.de/maps/search/${addressText}`} target="_blank" rel="noopener">
				<MapIcon />{ addressText }
			</a>
	
			{#if entry.telephone}
				<a href={`tel:${entry.telephone}`}>
					<PhoneIcon />{ entry.telephone }
				</a>
			{/if}
			
			{#if entry.email}
				<a href={`mailto:${entry.email}`}>
					<MailIcon />{ entry.email }
				</a>
			{/if}
			
			{#if entry.website}
				<a href={entry.website} target="_blank" rel="noopener">
					<GlobeIcon />{ entry.website }
				</a>
			{/if}
		</p>
		
		
		{#if entry.meta.offers}
			<p class="small-gap small-margin">
				<b> Angebote: </b>
				{#each entry.meta.offers as offer}
					<Tag title={mouseOverTexts[offer]}> {offerMapping[entry.type][offer]} </Tag>
				{/each}
			</p>
		{/if}
		
		{#if entry.meta.attributes}
			<p class="small-gap small-margin">
				<b> Eigenschaften: </b>
				{#each entry.meta.attributes as attribute}
					<Tag title={mouseOverTexts[attribute]}> {attributeMapping[entry.type][attribute]} </Tag>
				{/each}
			</p>
		{/if}
		
		{#if entry.meta.specials}
			<p>
				<b> Besonderheiten: </b> {entry.meta.specials}
			</p>
		{/if}
		
		{#if entry.meta.minAge}
			<p>
				<b> Mindestalter: </b> {entry.meta.minAge}
			</p>
		{/if}
	</div>
	
	<div class="controls">
		<LightButton>
			<EditIcon />
		</LightButton>
		
		<LightButton>
			<Share2Icon />
		</LightButton>
	</div>
</div>

<style lang="scss">
	@import "../scss/shadows";
	
	.entry {
		display: flex;
		background-color: var(--color-background-bright);
		box-shadow: $surface-shadow-soft;
		border-radius: 4px;
		padding: 10px 20px;
		
		.data {
			display: flex;
			flex-direction: column;
			flex: 1;
			
			p {
				display: flex;
				align-items: center;
				flex-wrap: wrap;
				gap: 10px 20px;
				margin: 0 0 20px 0;
				font-size: 0.9em;
				
				&:first-of-type{
					margin: 0 0 20px 5px;
				}
				
				&.small-gap {
					gap: 5px 10px;
				}
				
				&.small-margin {
					margin: 0 0 10px 0;
				}
				
				&:last-child {
					margin: 0;
				}
			}
			
			b {
				font-weight: 500;
			}
			
			h1 {
				display: flex;
				flex-wrap: wrap;
				align-items: center;
				gap: 0 10px;
				margin: 0;
				font-size: 1.4em;
				font-weight: 600;
			}
			
			.special-tag {
				padding: 0px 8px;
				border-radius: 4px;
				font-size: 0.6em;
				font-weight: 400;
				
				&.green {
					background-color: var(--color-special-highlight);
				}
				
				&.orange {
					background-color: var(--color-special-warn);
				}
			}
			
			a {
				display: inline-flex;
				align-items: center;
				gap: 5px;
				color: var(--color-edge);
				text-decoration: none;
				
				&:hover {
					text-decoration: underline;
				}
			}
			
			:global(.lucide) {
				height: 18px;
				width: 18px;
			}
		}
		
		.controls {
			display: flex;
			flex-direction: column;
			gap: 10px;
		}
	}
</style>

// components/Entry.vue
<template>

    <div class="entry">

        <p class="no-margin">
            <span class="heading">
                <h1>{{ entry.name }}</h1>
            </span>

            <span v-if="entry.accessible === 'true'" class="special highlight" :title="mouseOverTexts['barrierFree']">
                <CheckCircleIcon /> Barrierefrei
            </span>

            <span v-if="entry.accessible === 'false'" class="special warn" :title="mouseOverTexts['notBarrierFree']">
                <AlertTriangleIcon /> Nicht Barrierefrei
            </span>
        </p>

        <p class="inline-content">
            <b>{{ entry.firstName }} {{ entry.lastName }}</b>
            <span v-if="subjectMapping[entry.type]" :title="mouseOverTexts[entry.type]">{{ subjectMapping[entry.type][entry.meta.subject] }}</span>
            <span v-else :title="mouseOverTexts[entry.type]">{{ typeMapping[entry.type] }}</span>
        </p>
        
        <p>
            
            <a :href="`https://www.google.de/maps/search/${address}`" target="_blank">
                <map-icon />{{ address }}
            </a>
    
            <a v-if="entry.telephone" :href="`tel:${entry.telephone}`">
                <phone-icon />{{ entry.telephone }}
            </a>
            
            <a v-if="entry.email" :href="`mailto:${entry.email}`">
                <mail-icon />{{ entry.email }}
            </a>
            
            <a v-if="entry.website" :href="entry.website" target="_blank">
                <globe-icon />{{ website }}
            </a>
            
        </p>
        
        <p v-if="entry.meta.offers">
            <b>Angebote:</b> <Tag v-for="offer of entry.meta.offers" :key="offer" :title="mouseOverTexts[offer]">{{ offerMapping[entry.type][offer] }}</Tag>
        </p>
        
        <p v-if="entry.meta.attributes">
            <b>Bietet:</b> <Tag v-for="attr of entry.meta.attributes" :key="attr" :title="mouseOverTexts[attr]">{{ attributeMapping[entry.type][attr] }}</Tag>
        </p>
        
        <p v-if="entry.meta.specials">
            <b>Besonderheiten:</b>{{ entry.meta.specials }}
        </p>
        
        <p v-if="entry.distance" class="nav" :title="mouseOverTexts['distance']">
            <span>
                <NavigationIcon /> <b>{{ Math.round(entry.distance) }} km</b>
            </span>
        </p>
        
    </div>
    
</template>

<script>
import Tag from "@/components/utils/Tag";
import EntryMixin from "@/mixins/entry";
import MouseoverMixin from "@/mixins/mouseover";
import { MapIcon, MailIcon, GlobeIcon, PhoneIcon, NavigationIcon, CheckCircleIcon, AlertTriangleIcon } from "vue-feather-icons";

export default {
    name: "FullEntry",
    components: { Tag, MapIcon, MailIcon, GlobeIcon, PhoneIcon, NavigationIcon, CheckCircleIcon, AlertTriangleIcon },
    mixins: [ EntryMixin, MouseoverMixin ],
    props: {
        entry: Object
    },
    computed: {
        address: function () {
            return `${this.entry.address.street} ${this.entry.address.house}, ${this.entry.address.plz} ${this.entry.address.city}`;
        },
        website: function () {
            return new URL(this.entry.website).host;
        }
    }
}
</script>

<style scoped>

.entry {
    display: flex;
    flex-direction: column;
    background-color: var(--color-entry);
    box-shadow: 0px 0px 8px var(--color-box-shadow-rim), 0px 0px 16px var(--color-box-shadow-glow);
    border-radius: 4px;
    padding: 10px 20px;
    margin-bottom: 20px;
}

.entry h1 {
    font-size: 26px;
    margin: 0;
    font-weight: 600;
}

.entry > p {
    font-size: 16px;
    display: flex;
    flex-wrap: wrap;
    margin-top: 0;
}

.entry > p.no-margin {
    margin: 0;
}

.entry > p:last-child {
    margin-bottom: 5px;
}

.entry > p > span:not(.tag):not(.heading), .entry > p > a {
    color: var(--color-entry-details);
    display: flex;
    align-items: flex-start;
    margin-right: 20px;
    text-decoration: none;
    padding: 5px 0;
}

.entry > p > span.tag {
    margin: 2.5px;
}

.entry > p > span:last-child, .entry > p > span.tag:last-child {
    margin-right: 0;
}

.entry > p > span.heading {
    margin-right: 10px;
}

.entry b {
    font-weight: 500;
}

.entry > p > b {
    margin-right: 5px;
    display: inline-flex;
    align-items: center;
}

.entry > p.inline-content > span {
    margin-left: 5px;
}

.entry > p > span .feather, .entry > p > a .feather {
    margin-right: 5px;
    height: 18px;
    width: 18px;
    min-width: 18px;
}

.entry > p > a:hover {
    text-decoration: underline solid var(--color-entry-link-underline);
}

.entry > .nav {
    user-select: none;
}

.entry > p > .special {
    padding: 4px 6px 4px 4px !important;
    font-size: 13px;
    border-radius: 4px;
    height: min-content;
    align-self: center;
    cursor: default;
}

.entry > p > .special .feather {
    width: 16px;
    height: 16px;
    margin-right: 2px;
}

.entry > p > .highlight {
    background-color: var(--color-special-highlight);
}

.entry > p > .warn {
    background-color: var(--color-special-warn);
}

</style>
