// components/manage/EditableEntry.vue
<template>
    <div class="entry" :class="editable ? 'edit' : ''">
        <InlineTextField v-model="_entry.name" :editable="editable" heading="Name" class="col-1-2"/>
        <InlineSelectField v-model="_entry.type" :mapping="typeMappingData" :editable="editable" heading="Art" class="col-2-2"/>
        <InlineBooleanField v-model="_entry.approved" :editable="editable" heading="Freigeschaltet" class="no-border col-last row-first"/>

        <div class="segment col-1-2">
            <span>Adresse</span>
            <InlineTextField v-model="_entry.address.street" :editable="editable" heading="Straße" />
            <InlineTextField v-model="_entry.address.house" :editable="editable" heading="Hausnummer"/>
            <InlineTextField v-model="_entry.address.plz" :editable="editable" heading="PLZ"/>
            <InlineTextField v-model="_entry.address.city" :editable="editable" heading="Stadt"/>
            <span v-if="locWarn" class="warn">
                <AlertTriangleIcon />Dieser Eintrag hat keine Geodaten!
                
                <Button v-if="notRefetched && editable" :title="mouseOverTexts['reloadGeo']" @click="fetchGeo">erneut versuchen</Button>
            </span>
        </div>

        <div class="segment col-2-2">
            <span>Kontaktdaten</span>

            <InlineTextField v-model="_entry.firstName" class="half" :editable="editable" heading="Vorname"/>
            <InlineTextField v-model="_entry.lastName" class="half" :editable="editable" heading="Nachname"/>

            <InlineTextField v-model="_entry.website" :editable="editable" heading="Website"/>
            <InlineTextField v-model="_entry.email" :editable="editable" heading="E-Mail" />
            <InlineTextField v-model="_entry.telephone" :editable="editable" heading="Telefonnummer"/>
            <span v-if="infoWarn" class="warn">
                <AlertTriangleIcon />Dieser Eintrag hat keine Kontaktdaten!
            </span>
        </div>

        <InlineRadioList v-model="_entry.meta.attributes" :mapping="attributeMapping[_entry.type]" :editable="editable" heading="Attribute" class="col-1-3" />
        <InlineRadioList v-model="_entry.meta.offers" :mapping="offerMapping[_entry.type]" :editable="editable" heading="Angebote" class="col-2-3" />

        <div class="segment col-3-3">
            <InlineTextField v-model="_entry.meta.specials" :editable="editable" heading="Spezialangebote" />
            <InlineTextField v-model="_entry.meta.minAge" number :editable="editable" heading="Mindestalter" />
            <InlineSelectField v-if="subjectMapping[_entry.type]" v-model="_entry.meta.subject" :mapping="subjectMapping[_entry.type]" :editable="editable" heading="Fachrichtung" class="col-2-2"/>
            <InlineSelectField v-model="_entry.accessible" :mapping="accessibleMapping" :editable="editable" heading="Barrierefrei" />
        </div>

        <div class="buttons no-border">
            <Button v-if="editable" class="double" :title="mouseOverTexts['deleteEntry']" color="red" @click="deleteEntry"> löschen</Button>
            <Button v-if="editable" class="single" :title="mouseOverTexts['discardChanges']" icononly light @click="cancelEdit"> <XIcon /> </Button>
            <Button v-if="editable" class="single" :title="mouseOverTexts['saveChanges']" icononly @click="save"> <SaveIcon /> </Button>
            <Button v-if="!editable" class="single glow" :title="mouseOverTexts['copyLink']" icononly @click="copyLink"> <LinkIcon /> </Button>
            <Button v-if="!editable" class="single" :title="mouseOverTexts['editEntry']" icononly light @click="edit"> <EditIcon /> </Button>
        </div>
    </div>	
</template>

<script>
import EntryMixin from "@/mixins/entry";
import MouseoverMixin from "@/mixins/mouseover";

import InlineTextField from "./InlineTextField";
import InlineSelectField from "./InlineSelectField";
import InlineBooleanField from "./InlineBooleanField";
import InlineRadioList from "./InlineRadioList";

import { AlertTriangleIcon, Trash2Icon, EditIcon, SaveIcon, XIcon, LinkIcon } from 'vue-feather-icons';

import Button from "@/components/utils/Button";

export default {
    name: "CompactEntry",
    mixins: [ EntryMixin, MouseoverMixin ],
    components: { InlineTextField, InlineSelectField, InlineBooleanField, InlineRadioList,
        AlertTriangleIcon, Trash2Icon, EditIcon, SaveIcon, XIcon, LinkIcon,
        Button
    },
    data() {
        return {
            _entry: {},
            editable: false,
            notRefetched: false
        }
    },
    props: {
        entry: Object
    },
    computed: {
        locWarn() {
            return this._entry.approved && !this._entry.location;
        },

        infoWarn() {
            return !this._entry.website &&
                   !this._entry.email &&
                   !this._entry.telephone
        }
    },
    created() {
        this._entry = JSON.parse(JSON.stringify(this.entry));
        
        if (this._entry.accessible === undefined) this._entry.accessible = "unkown";
    },
    methods: {
        edit() {
            this.editable = true;
            this.notRefetched = true;
        },

        cancelEdit() {
            this.editable = false;
            this._entry = JSON.parse(JSON.stringify(this.entry));
        },

        deleteEntry() {
            if (window.confirm(`Bist du sicher, dass du den Eintrag "${this.entry.name}" löschen möchtest?`)) {
                this.$emit("delete", this.entry._id);
            }
        },

        fetchGeo() {
            this.notRefetched = false;
            this.$emit("fetchGeo", this.entry._id);
        },

        save() {
            let changes = this.getObjChanges(this.entry, this._entry);
            
            this.editable = false;

            this.$emit("save", this.entry._id, changes);
        },

        copyLink() {
            navigator.clipboard.writeText(`${window.location.origin}/manage/database?id=${this._entry._id}`);
            this.$okMsg("Link in die Zwischenablage kopiert!");
        },

        getObjChanges(original, changed) {
            let changes = {};

            for (const [key, val] of Object.entries(original)) {
                if (JSON.stringify(val) !== JSON.stringify(changed[key])) {
                    changes[key] = changed[key]
                }
            }

            return changes;
        }
    }
}
</script>

<style scoped>
.entry {
    display: grid;
    background-color: var(--color-entry);
    box-shadow: 0px 0px 8px var(--color-box-shadow-rim), 0px 0px 16px var(--color-box-shadow-glow);
    border-radius: 4px;
    padding: 5px 10px;
    margin-bottom: 20px;
    grid-template-columns: 2fr 1fr 1fr 2fr auto;
    column-gap: 8px;
    row-gap: 8px;
}

.col-1-2 {
    grid-column: 1 / 3;
}

.col-2-2 {
    grid-column: 3 / 5;
}

.col-last {
    grid-column: 5 / 6;
}

.col-1-3 {
    grid-column: 1 / 2;
}

.col-2-3 {
    grid-column: 2 / 4;
}

.col-3-3 {
    grid-column: 4 / 5;
}

.entry > * {
    box-shadow: 0 0 4px var(--color-box-shadow-rim);
    border-radius: 4px;
    
    padding: 2px 4px;
}

.no-border {
    box-shadow: none;
}

.segment {
    font-family: 'Poppins', sans-serif;
    font-weight: 400;
    font-size: 14px;
    color: var(--color-grey);
    display: grid;
    grid-template-columns: 1fr 1fr;
    align-content: start;
    column-gap: 4px;
    row-gap: 4px;
}

.segment > * {
    grid-column: 1 / 3;
}

.segment > .half {
    grid-column: auto / span 1;
}

.segment > .inline-field {
    font-size: 12px;
}

.warn {
    font-weight: 500;
    font-size: 15px;
    color: var(--color-warn);
    margin-top: auto;
    text-align: center;
    user-select: none;
    cursor: default;
}

.warn > .feather {
    display: inline-flex;
    align-self: center;
    width: 1em;
    height: 1em;
    top: 0.15em;
    position: relative;
    margin-right: 4px;
}

.warn > button {
    display: inline-flex;
    color: var(--color-entry);
    font-weight: 500;
    font-size: 13px;
    background-color: var(--color-warn);
    height: auto;
    padding: 0 6px;
}

.buttons {
    grid-column: 5 / 6;
    grid-row: 2 / 5;

    display: grid;
    grid-template-columns: auto auto;
    grid-template-rows: auto 1fr auto;

    justify-items: right;
    row-gap: 8px;
    column-gap: 8px;
}

.buttons > button {
    height: 40px;
}

.buttons > button:not(.icon-only) {
    padding: 12px;
}

.buttons > button:not(.double) {
    grid-row: 3 / 4;
}

.buttons > .double {
    grid-column: 1 / 3;
}

.buttons > .single {
    width: 40px;
    justify-content: center;
}

.buttons > .single > .feather {
    width: 22px;
    height: 22px;
}

.buttons > .glow {
    transition: background-color 0.6s;
}

.buttons > .glow:active {
    background-color: var(--color-radio-selected);
    transition: background-color 0s;
}

@media only screen and (max-width: 740px) {
    .entry {
        grid-template-columns: 1fr auto;
    }

    .col-1-2 {
        grid-column: 1 / 2;
    }

    .col-2-2 {
        grid-column: 1 / 2;
    }

    .segment > .col-2-2 {
        grid-column: 1 / 3;
    }

    .col-last {
        grid-column: 2 / 3;
    }

    .col-1-3 {
        grid-column: 1 / 2;
    }

    .col-2-3 {
        grid-column: 1 / 2;
    }

    .col-3-3 {
        grid-column: 1 / 2;
    }

    .row-first {
        grid-row: 1 / 2;
    }

    .buttons {
        grid-column: 2 / 3;
        grid-row: 7 / 8;
    }
}
</style>

// src/components/database/editableEntry.svelte
<script lang="ts">
	import type { Entry } from "$models/entry.model"
	
	import { typeMapping, offerMapping, attributeMapping, accessibleMapping, subjectMapping } from "$lib/entryMappings"
	import mouseOverTexts from "$lib/mouseOverTexts"
	
	import axios from "axios"
	import { getObjChanges, replaceFields } from "$lib/utils"
	import { popupOk, popupError } from "$components/popup.svelte"
	import { confirm } from "$components/confirm.svelte"
	
	import EditableInputField from "$components/database/editableInputField.svelte"
	import EditableSelectField from "$components/database/editableSelectField.svelte"
	import EditableCheckbox from "$components/database/editableCheckbox.svelte"
	import EditableRadioList from "$components/database/editableRadioList.svelte"
	import Button from "$components/elements/button.svelte"
	
	import AlertTriangleIcon from "lucide-icons-svelte/alertTriangle.svelte"
	import SaveIcon from "lucide-icons-svelte/save.svelte"
	import TrashIcon from "lucide-icons-svelte/trash.svelte"
	import EditIcon from "lucide-icons-svelte/edit.svelte"
	import XIcon from "lucide-icons-svelte/x.svelte"
	import LinkIcon from "lucide-icons-svelte/link.svelte"
	
	let edit: boolean = false;
	export let entry: Entry = null;
	
	// Deep copy
	let _entry: Entry = null;
	_entry = JSON.parse(JSON.stringify(entry));
	
	let noGeoData = false;
	$: noGeoData = _entry.approved && !_entry.location;
	
	let geoNotRefetched: boolean = false;
	
	let noContactDetails: boolean = false;
	$: noContactDetails = !_entry.website && !_entry.email && !_entry.telephone;
	
	function editEntry() {
		edit = true;
		geoNotRefetched = true;
	}
	
	function cancelEdit() {
		edit = false;
		_entry = JSON.parse(JSON.stringify(entry));
	}
	
	function copyLink() {
		navigator.clipboard.writeText(`${window.location.origin}/manage/database?id=${_entry._id}`);
		popupOk("Link in die Zwischenablage kopiert!");
	}
	
	async function saveChanges() {
		let changes = getObjChanges(entry, _entry);
		changes = replaceFields(changes, "", null);
		
		if (Object.keys(changes).length < 1) return;
		
		edit = false;
		
		try {
			await axios.patch(`entries/${_entry._id}/edit`, changes);
			
			entry = JSON.parse(JSON.stringify(_entry));
			
			popupOk("Änderungen gespeichert");
		} catch (e) {
			if (e.response) {
				popupError("Fehler beim Speichern: " + e.response.status);
			} else {
				popupError("Unbekannter Fehler beim Speichern");
			}
		}
	}
	
	async function deleteEntry() {
		let success: boolean = await confirm("Möchtest du diesen Eintrag wirklich löschen?");
		
		if (!success) return;
		
		try {
			await axios.delete(`entries/${_entry._id}`);
			popupOk("Eintrag gelöscht");
		} catch (e) {
			popupError("Unbekannter fehler beim Löschen");
		}
	}
</script>


<div class="editable-entry">
	<div class="auto-grid">
		<div class="header">
			<EditableInputField label="Name des Eintrags" bind:value={ _entry.name } { edit } />
			<EditableSelectField label="Kategorie" bind:value={ _entry.type } mapping={ typeMapping } { edit } />
			<EditableCheckbox label="Freigeschaltet" bind:checked={ _entry.approved } { edit } />
		</div>
		
		<div>
			<span class="group-title"> Adresse </span>
			<div class="sub-grid">
				<EditableInputField label="Straße" bind:value={ _entry.address.street } { edit } />
				<EditableInputField label="Hausnummer" bind:value={ _entry.address.house } { edit } />
				<EditableInputField label="Postleitzahl" bind:value={ _entry.address.plz } { edit } />
				<EditableInputField label="Stadt / Ort" bind:value={ _entry.address.city } { edit } />
			</div>
			
			{#if noGeoData}
				<span class="warn">
					<AlertTriangleIcon /> <span>Keine Geo-Daten vorhanden!</span>
				
					{#if edit && geoNotRefetched}
						<Button light title={mouseOverTexts["reloadGeo"]}>Erneut versuchen</Button>
					{/if}
				</span>
			{/if}
		</div>
		
		<div>
			<span class="group-title"> Kontaktdaten </span>
			
			<div class="sub-grid">
				<EditableInputField label="Vorname" bind:value={ _entry.firstName } { edit } />
				<EditableInputField label="Nachname" bind:value={ _entry.lastName } { edit } />
				
				<EditableInputField label="Webseite" bind:value={ _entry.website } { edit } />
				<EditableInputField label="E-Mail" bind:value={ _entry.email } { edit } />
				<EditableInputField label="Telefonnummer" bind:value={ _entry.telephone } { edit } />
			</div>
			
			{#if noContactDetails}
				<span class="warn">
					<AlertTriangleIcon /> <span>Dieser Eintrag hat keine Kontaktdaten!</span>
				</span>
			{/if}
		</div>
		
		<div class="sub-grid">
			<EditableRadioList label="Angebote" bind:value={ _entry.meta.offers } mapping={ offerMapping[_entry.type] } { edit } />
			<EditableRadioList label="Attribute" bind:value={ _entry.meta.attributes } mapping={ attributeMapping[_entry.type] } { edit } />
		</div>
		
		<div class="sub-grid">
			<EditableInputField label="Besonderheiten" bind:value={ _entry.meta.specials } { edit } />
			<EditableInputField label="Mindestalter" number bind:value={ _entry.meta.minAge } { edit } />
			
			{#if subjectMapping[_entry.type]}
				<EditableSelectField label="Fachrichtung" bind:value={ _entry.meta.subject } mapping={ accessibleMapping } { edit } />
			{/if}
			
			<EditableSelectField label="Barrierefrei" bind:value={ _entry.accessible } mapping={ accessibleMapping } { edit } />
		</div>
	</div>
	
	<div class="controls">
		{#if edit}
			<Button light iconOnly on:click={ saveChanges }  title={ mouseOverTexts["saveChanges"] }> <SaveIcon /> </Button>
			<Button light iconOnly on:click={ cancelEdit } title={ mouseOverTexts["discardChanges"] }> <XIcon /> </Button>
			<Button light iconOnly color="red" on:click={ deleteEntry } title={ mouseOverTexts["deleteEntry"] }> <TrashIcon /> </Button>
		{:else}
			<Button light iconOnly on:click={ editEntry } title={ mouseOverTexts["editEntry"] }> <EditIcon /> </Button>
			<Button light iconOnly on:click={ copyLink } title={ mouseOverTexts["copyLink"] }> <LinkIcon /> </Button>
		{/if}
	</div>
</div>

<style lang="scss">
	@import "../../scss/shadows";
	@import "../../scss/mixins";
	
	.editable-entry {
		display: flex;
		background-color: var(--color-background-bright);
		box-shadow: $surface-shadow-soft;
		border-radius: 4px;
		padding: 10px;
		gap: 10px;
		
		@include media-mobile {
			flex-direction: column;
		}
		
		.controls {
			display: flex;
			flex-direction: column;
			gap: 10px;
		}
		
		.group-title {
			font-size: 0.9em;
			font-weight: 500;
			margin-left: -2px;
			margin-top: -2px;
		}
		
		.header {
			display: grid;
			grid-template-columns: repeat(auto-fit, minmax(110px, 1fr));
			overflow: hidden;
			
			@include media-mobile {
				grid-template-columns: 1fr;
			}
			
			gap: 10px;
			grid-column: 1 / -1;
			
			:global(div) {
				grid-column: span 2;
				
				@include media-mobile {
					grid-column: unset;
				}
			}
			:global(div:last-child) {
				grid-column: span 1;
			}
		}
	}
	
	.auto-grid {
		display: grid;
		flex-grow: 1;
		gap: 10px;
		grid-template-columns: repeat(auto-fit, minmax(380px, 1fr));
		
		@include media-mobile {
			grid-template-columns: minmax(0, 1fr);
		}
		
		:global(.lucide) {
			height: 18px;
			width: 18px;
			min-height: 18px;
			min-width: 18px;
		}
		
		// Every div element (including components) that is in the entry gets a border
		& > :global(div) {
			border-radius: 4px;
			padding: 5px 8px;
			border: 1px solid var(--color-rim-bright);
		}
		
		& > div {
			display: flex;
			flex-direction: column;
			gap: 10px;
			
			span {
				font-size: 0.8em;
				color: var(--color-edge-dimmed);
			}
		}
		
		.sub-grid {
			display: grid;
			grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
			min-width: 0;
			
			@include media-mobile {
				grid-template-columns: minmax(0, 1fr);
			}
			
			gap: 10px;
		}
		
		.warn {
			display: flex;
			align-items: center;
			justify-content: flex-start;
			gap: 10px;
			min-height: 35px;
			
			&, span {
				color: var(--color-edge-warn);
				font-size: 15px;
			}
			
			:global(button) {
				min-height: unset;
			}
		}
	}
</style>
