// src/components/elements/tag.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	interface Props {
		children?: Snippet;
		[key: string]: unknown;
	}

	let { children, ...rest }: Props = $props();
</script>

<span class="tag" {...rest}>
	{#if children}{@render children()}{/if}
</span>

<style lang="scss">
	.tag {
		display: inline-flex;
		background-color: var(--color-surface-bright);
		padding: 3px 8px;
		border-radius: 4px;
		cursor: default;
	}
</style>

// components/utils/Tag.vue
<template>

    <span class="tag">
        <slot />
    </span>
    
</template>

<script>
export default {
name: "Tag"
}
</script>

<style scoped>

.tag {
    display: inline-flex;
    background-color: var(--color-light);
    padding: 3px 8px;
    border-radius: 4px;
    cursor: default;
}

</style>
