// components/utils/Popup.vue
<template>
	<div class="popup" @click="visible = false" :class="[popup.type, visible ? 'visible' : '']">
		<CheckCircleIcon v-if="popup.type === 'ok'" />
		<AlertCircleIcon v-if="popup.type === 'warn'" />
		<XCircleIcon v-if="popup.type === 'error'" />
		<span>{{ popup.text }}</span>
	</div>
</template>

<script>
import { AlertCircleIcon, CheckCircleIcon, XCircleIcon } from "vue-feather-icons";

export default {
	components: { AlertCircleIcon, CheckCircleIcon, XCircleIcon },
	data() {
		return {
			visible: false,
			id: 0
		}
	},
	computed: {
		popup() {
			if (this.$store.state.popup.text !== "") {
	this.showPopup();
			}

			return this.$store.state.popup;
		}
	},
	methods: {
		showPopup() {
			this.visible = true;

			this.id += 1;
			let id = this.id;

			setTimeout(() => {

	if (id === this.id) this.visible = false;

			}, 4000);
		}
	}
}
</script>

<style scoped>

.popup {
	position: fixed;
	margin-left: auto;
	margin-right: auto;
	left: 16px;
	right: 16px;
	bottom: 3em;

	max-width: 380px;
	width: fit-content;
	display: flex;
	flex-direction: row;
	align-items: center;

	background-color: var(--color-popup-default);

	padding: 10px 12px;
	border-radius: 4px;
	box-shadow: 0px 0px 8px var(--color-box-shadow-rim), 0 0 16px var(--color-box-shadow-glow);
	color: white;

	visibility: hidden;
	opacity: 0%;
	transition: opacity 1.4s;
	transition: visibility 0s linear 1.4s, opacity 1.4s;

	font-family: 'Fira Sans', sans-serif;
	font-size: 18px;

	pointer-events: none;
}

.popup > span {
	margin-left: 8px;
}

.popup > .feather {
	min-width: 22px;
	min-height: 22px;
}

.popup.visible {
	cursor: pointer;
	pointer-events: unset;

	visibility: visible;
	opacity: 100%;
	transition: visibility 0s linear 0s, opacity 300ms;
}

.popup.ok {
	background-color: var(--color-popup-ok);
}

.popup.warn {
	background-color: var(--color-popup-warn);
}

.popup.error {
	background-color: var(--color-popup-error);
}

</style>

// src/components/popup.svelte
<script lang="ts" context="module">	
	import { writable } from "svelte/store"
	import config from "$lib/config"
	
	let visible = writable(false);
	let type = writable("ok");
	let text = writable("");
	
	let id = 0;
	
	function popup(message: string, _type: string) {
		visible.set(true);
		text.set(message);
		type.set(_type);
		
		id += 1;
		let currentId = id;
		
		setTimeout(() => {
			// only run, if no new popups were called since timer started
			if (id === currentId) {
				visible.set(false);
			}
		}, config.client.popupLinger);
	}
	
	export function popupOk(message: string) {
		popup(message, "ok");
	}
	
	export function popupWarn(message: string) {
		popup(message, "warn");
	}
	
	export function popupError(message: string) {
		popup(message, "error");
	}
</script>

<script lang="ts">
	import AlertIcon from "lucide-icons-svelte/alertCircle.svelte"
	import CheckCircleIcon from "lucide-icons-svelte/checkCircle.svelte"
	import XCircleIcon from "lucide-icons-svelte/xCircle.svelte"
</script>

<div class="popup { $type } { $visible ? 'visible' : '' }" on:click={() => $visible = false}>
	{#if $type === "ok"}
		<CheckCircleIcon size="22px" />
	{:else if $type === "warn"}
		<AlertIcon size="22px" />
	{:else if $type === "error"}
		<XCircleIcon size="22px" />
	{/if}
	<span> { $text } </span>
</div>

<style lang="scss">
	@import "../scss/shadows";
	
	.popup {
		position: fixed;
		margin-left: auto;
		margin-right: auto;
		left: 16px;
		right: 16px;
		bottom: 82px;
		
		max-width: 380px;
		width: fit-content;
		
		display: flex;
		flex-direction: row;
		align-items: center;
		
		padding: 10px 12px;
		border-radius: 4px;
		
		color: var(--color-edge-bright);
		box-shadow: $surface-shadow-soft;
		font-family: 'Fira Sans', sans-serif;
		font-size: 18px;
		
		pointer-events: none;
		
		visibility: hidden;
		opacity: 0;
		transition: visibility 0s linear 1.4s, opacity 1.4s;
		
		&.visible {
			cursor: pointer;
			pointer-events: unset;
			
			visibility: visible;
			opacity: 1;
			transition: visibility 0s linear 0s, opacity 300ms;
		}
		
		&.ok {
			background-color: var(--color-popup-ok);
		}
		
		&.warn {
			background-color: var(--color-popup-warn);
		}
		
		&.error {
			background-color: var(--color-popup-error);
		}
		
		span {
			margin-left: 8px;
		}
		
		:global(.lucide) {
			min-width: 22px;
			min-height: 22px;
		}
	}
</style>
