// components/utils/Button.vue
<template>

    <button :class="[color, light ? 'light' : '', center ? 'center' : '', icononly ? 'icon-only' : '']" @click="click">
        <slot v-if="!loading" />
        <Loader v-else :dark="light" />
    </button>
    
</template>

<script>
import Loader from "@/components/utils/Loader";

export default {
    name: "Button",
    components: {Loader},
    props: {
        light: Boolean,
        center: Boolean,
        color: String,
        loading: Boolean,
        icononly: Boolean
    },
    methods: {
        
        click: function () {
            this.$emit("click");
        }
        
    }
}
</script>

<style scoped>

button {
    border: 0;
    color: white;
    background-color: var(--color-dark);
    box-shadow: 0 3px 6px var(--color-box-shadow);
    cursor: pointer;
    font-size: 16px;
    display: flex;
    align-items: center;
    font-weight: 600;
    padding: 8px 16px;
    border-radius: 4px;
    outline: 0;
    transition: 0.12s ease background-color;
    font-family: 'Poppins', sans-serif;
}

button:not(.light) {
    height: 40px;
}

button:hover, button:focus {
    background-color: var(--color-dark-accent);
}

button:active {
    background-color: var(--color-dark-active);
}

.red {
    background-color: var(--color-red);
}

.red:hover, .red:focus {
    background-color: var(--color-red-accent);
}

.red:active {
    background-color: var(--color-red-active);
}

.feather {
    stroke-width: 3;
    margin-right: 5px;
    width: 18px;
    height: 18px;
}

.icon-only {
    padding: 8px;
}

.icon-only .feather {
    margin: 0;

    min-width: 18px;
    min-height: 18px;
}

.light {
    background-color: var(--color-light);
    box-shadow: none;
    color: #334450;
    padding: 5px 10px;
}

.light:hover, .light:focus {
    background-color: var(--color-light-accent);
}

.light:active {
    background-color: var(--color-light-active);
}

.center {
    justify-content: center;
    align-items: center;
}

@media only screen and (max-width: 720px) {
    
    .light .feather {
        margin: 0;
    }
    
}
</style>

// src/components/elements/button.svelte
<script lang="ts">
	import Loader from "$components/elements/loader.svelte"
	
	export let color: string = "";
	export let loading = false;
	export let light = false;
	export let iconOnly = false;
</script>

<button on:click class={ color } class:light class:iconOnly {...$$props}>
	{#if loading}
		<Loader dark={ light } />
	{:else}
		<slot></slot>
	{/if}
</button>

<style lang="scss">
	@import "../../scss/shadows.scss";
	
	button {
		border: 0;
		color: white;
		background-color: var(--color-surface-primary);
		cursor: pointer;
		font-size: 0.9em;
		display: flex;
		align-items: center;
		justify-content: center;
		font-weight: 600;
		padding: 8px 16px;
		border-radius: 4px;
		outline: 0;
		transition: 0.12s ease background-color;
		font-family: "Poppins", sans-serif;
		
		&:hover,
		&:focus {
			background-color: var(--color-surface-primary-hover);
		}
		
		&:active {
			background-color: var(--color-surface-primary-active);
		}
		
		/* shadows */
		
		&:not(.light) {
			box-shadow: $surface-shadow-soft;
		}
		
		&:hover:not(.light),
		&:focus:not(.light) {
			box-shadow: $surface-shadow-strong;
		}
		
		/* icons */
		
		:global(.lucide) {
			stroke-width: 3;
			margin-right: 5px;
			width: 20px;
			height: 20px;
		}
		
		&.iconOnly {
			padding: 8px;
			
			:global(.lucide) {
				margin: 0;
			}
		}
		
		/* lightweight button */
		
		&.light {
			background-color: var(--color-surface-bright);
			
			&:not(.red) {
				color: var(--color-edge);
			}
			
			padding: 5px 10px;
			min-height: 35px;
			
			&.iconOnly {
				padding: 7.5px;
			}
			
			&:hover,
			&:focus {
				background-color: var(--color-surface-bright-hover);
			}
			
			&:active {
				background-color: var(--color-surface-bright-active);
			}
		}
		
		/* colored button */
		&.red {
			background-color: var(--color-surface-warn);
		}

		&.red:hover,
		&.red:focus {
			background-color: var(--color-surface-warn-hover);
		}

		&.red:active {
			background-color: var(--color-surface-warn-active);
		}
	}
</style>
