// components/utils/Errorbox.vue
<template>
	<span class="errorbox" :class="invalid ? 'invalid' : ''">
		<span v-if="invalid" class="error">{{errorMSG}}</span>
		<slot />
	</span>
</template>

<script>
export default {
	name: "Errorbox",
	props: [
		"invalid",
		"errorMSG"
	]
}
</script>

<style>
span.invalid .checkbox-container:last-child {
	margin-bottom: 0px;
}
</style>

<style scoped>

span {
	position: relative;
}

span.invalid {
	content: "";
	border-radius: 4px;
	border: 2px solid var(--color-error);
	padding: 6px 4px;
	margin-bottom: 20px;
}

span .error {
	position: absolute;
	color: var(--color-error);
	font-size: 12px;
	top: -14px;
	left: 0;
}

</style>

// src/components/elements/errorBox.svelte
<script lang="ts">
	export let error = "";
	
	$: isError = error && error.length > 0;
</script>

<span class:isError>
	{#if isError}
		<span class="error">{error}</span>
	{/if}
	
	<slot></slot>
</span>

<style lang="scss">
	span {
		display: flex;
		flex-direction: column;
		position: relative;
		
		&.isError {
			border-radius: 4px;
			border: 2px solid var(--color-edge-error);
			padding: 6px 4px;
			margin-bottom: 20px;
			
			:global(.checkbox-container:last-child) {
				margin-bottom: 0;
			}
		}
		
		.error {
			font-size: 14px;
			font-weight: 500;
			color: var(--color-edge-error);
			position: absolute;
			left: 0;
			top: -18px;
		}
	}
</style>
